# Generated by Django 3.2.2 on 2021-05-13 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255)),
                ('ordering', models.IntegerField(default=0, verbose_name='Сортировка по счету (навбар)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать на главной странице')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='theblog.category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование Товара')),
                ('slug', models.SlugField(max_length=255)),
                ('body', models.TextField(blank=True, null=True, verbose_name='Описание Товара')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('snippet', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='theblog.category', verbose_name='Категория')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='theblog.post', verbose_name='Родитель')),
            ],
            options={
                'verbose_name_plural': 'Статьи',
                'ordering': ('-post_date',),
            },
        ),
    ]
