# Generated by Django 3.2.2 on 2021-05-17 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0006_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/profile/', verbose_name='Фото профиля')),
                ('website_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Сайт')),
                ('instagram_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram')),
                ('twitter_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Призвание')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
