# Generated by Django 3.2.2 on 2021-05-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_added']},
        ),
    ]
